[package]
name = "njust_thesis_typst_template"
version = "0.1.0"
entrypoint = "lib.typ"
repository = "https://github.com/Hobr/njust_thesis_typst_template/"
authors = ["Hobr"]
license = "MIT"
description = "南京理工大学Typst论文模板"
keywords = ["Nanjing University of Science and Technology", "thesis"]
categories = ["thesis"]
exclude = [".vscode"]

[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "thumbnail.png"
